# Site settings
title: Ol (Otus Lisp)
email: otus.lisp@mail.com
description: Otus Lisp home page
baseurl: ""
url: "http://otus-lisp.github.io"

plugins:
#  - jekyll-sitemap
  - jemoji

# Build settings
markdown: kramdown
